### PR TITLE
Fix regex for https replacement in host field

### LINKED ISSUE #1: BOM upload failed
I tried upload bom.xml to dependency track server and it gets failed. 
messages:
HTTP request failed. See error message:
 http: nodename nor servname provided, or not known.

my configurations:

dtrackPublishBom{
    host "http://localhost:8081"
    apiKey "ddGoq9pjLQqR6YZjNh1mcc24IALZxx"
    projectUuid "fc7b4602-e2dd-4823-b36a-e64080d68880"
    realm "/api/v1/bom"
    bomFile file("build/reports/bom.xml")
}
publishBom.dependsOn(cyclonedxBom)

it saying node or servername not provided

### PR DESCRIPTION
**Pull request by mkep-dev**

### CODE REVIEW

File: src/main/java/com/github/mkepDev/dependencyTrackBomPublish/DependencyTrackPublishBomTask.java [hunk 1]
```diff
@@ -149,7 +150,9 @@ private void publishData(String host, String realm, String apiKey, String projec
             realm = realm.substring(0, host.length() - 1);
         }
 
-        String dtrackUrl = "http://" + host.replaceAll("http%://", "") + "/" + realm;
+        logger.info("Use new reqex");
+
+        String dtrackUrl = "http://" + host.replaceAll("https?://", "") + "/" + realm;
```
Comment (112233445566778899a) [inline src/main/java/com/github/mkepDev/dependencyTrackBomPublish/DependencyTrackPublishBomTask.java:155]: Hi, I found your project really useful and I would like to use your plugin with https protocol for security reasons. Is there any specific reason why you replace https with http here?

Comment (mkep-dev) [reply src/main/java/com/github/mkepDev/dependencyTrackBomPublish/DependencyTrackPublishBomTask.java:155]: Hi

to be honest: I was just lazy.
The Docker image of dependency-track that I use, relies on a self signed-cert and there was no need to use https in my local network.

You can create a PR or wait for a few days and I will adjust this.
